services:
  - type: web
    name: vigia-integridad
    runtime: python
    pythonVersion: "3.12.0"
    buildCommand: pip install --upgrade pip
    startCommand: python servidor.py
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.12.0"
    plan: free
